### ISSUE TITLE
Chapter 3 Tests Fail : syntax error on line 26 : FAILURE HEADER

### ISSUE THREAD

**Issue by fpcodebase** [maxwelld90/tango_with_django_2_code#15]
Completed exercises until end of Chapter 3.
Upon executing the tests for chapter 3 get following error:

  **File "/home/aspma/python/django/tango_with_django_project/rango/tests_chapter3.py", line 26
    FAILURE_HEADER = f"{os.linesep}{os.linesep}{os.linesep}================{os.linesep}TwD TEST FAILURE =({os.linesep}================{os.linesep}"**
  
----------------------------------------------- Console Output --------------------------------------------                                                                                                                                                
SyntaxError: invalid syntax

(rangoenv) aspma@aspma-VirtualBox:~/python/django/tango_with_django_project$ python manage.py test rango.tests_chapter3
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/core/management/commands/test.py", line 56, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/test/runner.py", line 603, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/home/aspma/Envs/rangoenv/lib/python3.5/site-packages/django/test/runner.py", line 485, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "/usr/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/aspma/python/django/tango_with_django_project/rango/tests_chapter3.py", line 26
    FAILURE_HEADER = f"{os.linesep}{os.linesep}{os.linesep}================{os.linesep}TwD TEST FAILURE =({os.linesep}================{os.linesep}"
                                                                                                                                                  ^
SyntaxError: invalid syntax

----------------------------------------------- Console Output --------------------------------------------

**Comment by maxwelld90** [comment]
Hi @energyflowprogram,
Strange error. What version of Python are you running this on?

**Comment by fpcodebase** [comment]
Yes, quite strange.

Python version is 3.5.2

----------------------------------------------- Console Output --------------------------------------------
(rangoenv) aspma@aspma-VirtualBox:~/python/django/fpdjangorepo$ python -V
Python 3.5.2
----------------------------------------------- Console Output --------------------------------------------

**Comment by maxwelld90** [comment]
Oh, you need to be running at least Python 3.6 for the tests to work. We use _f-strings_ to create output. Python 3.5 does not understand this syntax.

**Comment by fpcodebase** [comment]
Thanks David.
Upgrading python to 3.6 version. 
Will post the results shortly

**Comment by fpcodebase** [comment]
Worked with Python 3.6

----------------------------------------------- Console Output --------------------------------------------
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............
----------------------------------------------------------------------
Ran 12 tests in 0.056s

OK

----------------------------------------------- Console Output --------------------------------------------
Destroying test database for alias 'default'...

**Comment by fpcodebase** [comment]
Closing issue

**Comment by maxwelld90** [comment]
Nice one, glad you got it to work.

All the best!
